---
language: python
python: "3.6.1"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install dependences
  - make setup
  # Check ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - make test.lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
